---
abstract: 'Access control'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-AccessControl
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mojolicious: 2.63
  Net::CIDR::Lite: 0.21
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hayajo/Mojolicious-Plugin-AccessControl.git
version: 0.02
